language: cpp
compiler:
- clang
- gcc
python:
- 3.6
#matrix:
#  include:
#  - os: osx
#    language: objective-c
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
install:
#- brew install python3
#- brew install --overwrite numpy --with-python3
- python -V
- "hg clone -b CMake https://bitbucket.org/Coin3D/coin coin"
- "cmake coin/CMakeLists.txt"
- "make -C coin"
script:
# skip building PyInventor on OSX as only python 2.7 is available
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then python setup.py --libpath ./coin/src/ --incpath ./coin/include/ build; fi
