language: python

matrix:
  include:
#    - os: linux
#      python: 3.6
#      compiler: gcc
#      env: 
#        - CXX="g++" 
#        - CC="gcc"
#    - os: linux
#      python: 3.6
#      compiler: clang
#      env: 
#        - CXX="clang++" 
#        - CC="clang"
#    - os: osx
#      language: generic
    - os: osx
      language: generic
      osx_image: xcode8.3

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  # update brew and pyenv on macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; if (brew outdated | grep pyenv > /dev/null); then brew upgrade pyenv; fi; fi
  # install Python 3.6.1 on macOS
  - export PYTHON=python
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.6.1; export PYTHON=$HOME/.pyenv/versions/3.6.1/bin/python; fi
  # make sure numpy is installed
  - $PYTHON -m pip install numpy

install:
  - "hg clone -b CMake https://bitbucket.org/Coin3D/coin coin"
  - "cmake coin/CMakeLists.txt"
  - "make -C coin"

script:
  # only build PyInventor if Python 3.x.x
  - if [[ $($PYTHON --version 2>&1) == *3\.?\.? ]]; then $PYTHON setup.py --libpath ./coin/src/ --incpath ./coin/include/ build; fi
