language: python

matrix:
  include:
    - os: linux
      python: 3.6
      compiler: gcc
      env: 
        - CXX="g++" 
        - CC="gcc"
    - os: linux
      python: 3.6
      compiler: clang
      env: 
        - CXX="clang++" 
        - CC="clang"
    - os: osx
      language: generic

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

install:
#- brew install python3
#- brew install --overwrite numpy --with-python3
- python -V
- echo "CXX=$CXX"
- echo "version `$CXX --version`"
#- "hg clone -b CMake https://bitbucket.org/Coin3D/coin coin"
#- "cmake coin/CMakeLists.txt"
#- "make -C coin"
script:
# skip building PyInventor on OSX as only python 2.7 is available
#- if [[ $(python --version 2>&1) == *3\.?\.? ]]; then python setup.py --libpath ./coin/src/ --incpath ./coin/include/ build; fi
