language: python
python:
- "3.6"
matrix:
  include:
  - os: osx
    language: objective-c
install:
- brew install python3
- brew install --overwrite numpy --with-python3
- "hg clone -b CMake https://bitbucket.org/Coin3D/coin coin"
- "cmake coin/CMakeLists.txt"
- "make -C coin"
script:
- python3 setup.py --libpath ./coin/src/ --incpath ./coin/include/ build
