language: python

matrix:
  include:
#    - os: linux
#      python: 3.6
#      compiler: gcc
#      env: 
#        - CXX="g++" 
#        - CC="gcc"
#    - os: linux
#      python: 3.6
#      compiler: clang
#      env: 
#        - CXX="clang++" 
#        - CC="clang"
#    - os: osx
#      language: generic
    - os: osx
      language: generic
      osx_image: xcode8.3

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

install:
  - pyenv install 3.6.1
  - pyenv virtualenv 3.6.1 env36
  - pyenv activate env36
  - python --version
  #- brew install python3
  #- brew install --overwrite numpy --with-python3
  #- "hg clone -b CMake https://bitbucket.org/Coin3D/coin coin"
  #- "cmake coin/CMakeLists.txt"
  #- "make -C coin"

script:
  # only build PyInventor if Python 3.x.x
  - if [[ $(python --version 2>&1) == *3\.?\.? ]]; then python setup.py --libpath ./coin/src/ --incpath ./coin/include/ build; fi
