language: python

matrix:
  include:
    #- os: linux
    #  python: 3.6
    #  compiler: gcc
    #  sudo: required
    #  env: 
    #    - CXX="g++" 
    #    - CC="gcc"
    #- os: linux
    #  python: 3.6
    #  compiler: clang
    #  sudo: required
    #  env: 
    #    - CXX="clang++" 
    #    - CC="clang"
    - os: osx
      language: generic
    - os: osx
      language: generic
      osx_image: xcode8.3

addons:
  apt:
    # linux workers have very outdated cmake and mercurial installed, need to update
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - mercurial

before_install:
  # update brew and pyenv on macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; if (brew outdated | grep pyenv > /dev/null); then brew upgrade pyenv; fi; fi
  # install Python 3.6.1 on macOS
  - export PYTHON=python
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.6.1; export PYTHON=$HOME/.pyenv/versions/3.6.1/bin/python; fi
  # make sure numpy is installed
  - $PYTHON -m pip install numpy

install:
  - export COININC=inst/include
  - export COINLIB=inst/lib
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export COININC=inst/Inventor.framework/Resources/include; export COINLIB=inst/Inventor.framework/Libraries; fi; 
  - hg clone --insecure https://bitbucket.org/Coin3D/simage simage
  - cmake simage/CMakeLists.txt -DCMAKE_INSTALL_PREFIX=inst
  - make -C simage install 
  - hg clone --insecure https://bitbucket.org/Coin3D/coin coin
  - mkdir coin_build
  - cmake -Bcoin_build -Hcoin -DCMAKE_INSTALL_PREFIX=inst -DCOIN_BUILD_DOCUMENTATION=OFF
  - make -C coin_build install
  - $PYTHON setup.py install --incpath $COININC --libpath $COINLIB

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COINLIB
  - export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$COINLIB
  - coin/testsuite/CoinTests
  - $PYTHON -m unittest --verbose tests/test_smoke.py
