language: python

matrix:
  include:
    - os: linux
      python: 3.6
      compiler: gcc
      sudo: required
      env: 
        - CXX="g++" 
        - CC="gcc"
    - os: linux
      python: 3.6
      compiler: clang
      sudo: required
      env: 
        - CXX="clang++" 
        - CC="clang"
    - os: osx
      language: generic
    - os: osx
      language: generic
      osx_image: xcode8.3

addons:
  apt:
    # linux workers have very outdated cmake installed, need to update
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  # update brew and pyenv on macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; if (brew outdated | grep pyenv > /dev/null); then brew upgrade pyenv; fi; fi
  # install Python 3.6.1 on macOS
  - export PYTHON=python
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.6.1; export PYTHON=$HOME/.pyenv/versions/3.6.1/bin/python; fi
  # make sure numpy is installed
  - $PYTHON -m pip install numpy

install:
  - export COINDIR=inst
  - hg clone https://bitbucket.org/Coin3D/simage simage
  - cmake simage/CMakeLists.txt -DCMAKE_INSTALL_PREFIX=$COINDIR
  - make -C simage install
  - hg clone https://bitbucket.org/Coin3D/coin coin
  - cmake coin/CMakeLists.txt -DCMAKE_INSTALL_PREFIX=$COINDIR
  - make -C coin install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COINDIR/lib
  - $PYTHON setup.py install

script:
  - coin/testsuite/CoinTests
  - $PYTHON -m unittest --verbose tests/test_smoke.py
